# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://ablot.github.io/learn2dev/"

git_url = "https://github.com/ablot/learn2dev/tree/master/"

def custom_doc_links(name): return None
